name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_to_heroku:
    strategy:
      matrix:
        os: [ubuntu-latest] # No need to add windows or mac
        node-version: [16.x]
        mongodb-version: ['5.0.6']

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      #- name: Start MongoDB
      #  uses: supercharge/mongodb-github-action@1.7.0
      #  with:
      #    mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.11

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm' # From https://pnpm.io/continuous-integration

      - name: Install deps
        run: pnpm i --frozen-lockfile --strict-peer-dependencies

      - name: build the app
        run: pnpm run build
      
      #- name: run test
      #  run: pnpm run test
        
      - name: Login heroku
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      - name: Add Heroku remote
        run: heroku git:remote --app $HEROKU_APP_NAME
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      - run: git checkout main
      - name: Push to Heroku
        run: git push heroku main
